### ISSUE TITLE
What are the requirements for Inference of the pre trainned model?

### ISSUE THREAD

**Issue by orenong** [openai/image-gpt#1]
what are the minumum requirements for Inference?
thanks

**Comment by chenmarkGH** [comment]
A single 16GB GPU suffices for sampling and evaluating iGPT-L.

**Comment by orenong** [comment]
can it work with CPU?

**Comment by orenong** [comment]
Can I run it on the CPU?
and also, a theoretical question, if it works on 16GB vram, will it also work with 3 6GB GPUs?

**Comment by cybersatori** [comment]
> Can I run it on the CPU?


+1

**Comment by KosayJabre** [comment]
Does your +1 mean yes? I'm also interested in knowing if this would run on CPU with 32GB or 64GB of RAM.

**Comment by skull3r7** [comment]
> Does your +1 mean yes? I'm also interested in knowing if this would run on CPU with 32GB or 64GB of RAM.

yes it works, but it is extremely slow.
