### ISSUE TITLE
size mismatch for centroids: copying a param with shape torch.Size([512, 3]) from checkpoint, the shape in current model is torch.Size([16, 3]).

### ISSUE THREAD

**Issue by Muhammad-Zubair** [openai/image-gpt#11]
**After compute centroids**
!python src/compute_centroids.py --dataset cifar10 --num_clusters=16
**I tried to train with this command**
!python src/run.py --dataset cifar-10-batches-py train configs/s_clf.yml --pretrained=models/cifar10_gen.ckpt
**Also tried to generate samples with this command**
!python src/sample.py models/cifar10_gen.ckpt

**but got this error:-**

Traceback (most recent call last):
File "src/run.py", line 91, in
args.func(args)
File "src/run.py", line 21, in train
model = ImageGPT.load_from_checkpoint(args.pretrained)
File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 154, in load_from_checkpoint
model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 200, in _load_model_state
model.load_state_dict(checkpoint['state_dict'], strict=strict)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
self.class.name, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ImageGPT:
size mismatch for centroids: copying a param with shape torch.Size([512, 3]) from checkpoint, the shape in current model is torch.Size([16, 3]).

**Comment by chenmarkGH** [comment]
Sorry, I'm not sure what script you're running - there is no src/compute_centroids.py in master. The default number of color clusters is 512 for this repository, so perhaps your error is related to your command being run with 16 clusters.
