### ISSUE TITLE
A quick question: the provided code does not include model training?

### ISSUE THREAD

**Issue by roadjiang** [openai/image-gpt#8]
If so, would you plan to release the training part?

**Comment by d12306** [comment]
agree, need for pretraining code!

**Comment by cellininicholas** [comment]
Any news on this, or advice on where to look for more information?

**Comment by chenmarkGH** [comment]
Sorry, following the precedent of [GPT-2](https://github.com/openai/gpt-2/issues/19), we are not releasing training code for now. If you follow the link, you'll find working third-party training code. Given that the diff from GPT-2 is very small, the same training code should work for iGPT too.

For hyperparameters, see Appendix A of our paper and for pre-training details, see Section 3.4.
